### PR TITLE
Swift 4.2 update

### PR DESCRIPTION
**Pull request by kdvmgn**

### CODE REVIEW

**Comment by Steven4294** [comment]
can we merg this and update pod spec?

**Comment by DrowsySquirrel** [comment]
can we merge this and make a new release?

**Comment by takuoka** [comment]
Sorry! 💦 
Now I added you3 as collaborator of this repo! 😃

**Comment by takuoka** [comment]
Of cource, you can merge this and can update podspec and can make new release! 👍

**Comment by DrowsySquirrel** [comment]
@entotsu Still can't find the merge button.

**Comment by takuoka** [comment]
@DoraemonSoon 
Wow.. 💧 
It looks like I invited you, but it seems that you need your approval.
I tried to send the invitation mail again.
Please check your e-mail and approve it! 🙏

**Pull request merged**
